name: Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm ci

            - run: npm run build

            - name: Generate Release Notes
              id: notes
              uses: actions/github-script@v7
              with:
                  script: |
                      const { data } = await github.rest.repos.generateReleaseNotes({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        tag_name: context.ref.replace("refs/tags/", "")
                      });

                      const fs = require('fs');
                      fs.writeFileSync('RELEASE_NOTES.md', data.body);

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  body_path: RELEASE_NOTES.md
                  files: dist/timeline_card.js
                  prerelease: ${{ contains(github.ref, '-') }}
